daysUntilStale: 360
daysUntilClose: 7
exemptLabels:
  - prospect
  - foundational
  - wanted
  - bug
markComment: >
  There has been no activity on this issue for 1 years. It will be
  automatically closed in 1 weeks.

  If the issue is still relevant, please briefly explain (or remove the label).
  Feel free to reopen at any time.
closeComment: false
